language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
# environment setting
env:
  - DJANGO=1.11.5
# command to run tests
script:
  - pytest # python unit test
  - python manage.py test # Django test