# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20170918_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together=set([('project', 'title'), ('project', 'order')]),
        ),
    ]
