# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_activitylog_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='membres',
            new_name='members',
        ),
    ]
